pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/panupongth148/Project-SW-DEV-TOOLS-AND-ENV-Group4'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd frontend && npm install'
            }
        }
        stage('Run unit test') {
            steps {
                sh 'cd frontend && npm run test:unit'
            }
        }
        stage('Run component test') {
            steps {
                sh 'cd frontend && npm test:com'
            }
        }
    }
}