pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/panupongth148/Project-SW-DEV-TOOLS-AND-ENV-Group4'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        stage('Run unit test') {
            steps {
                   echo 'cd backend && npm run test'
            }
        }
        stage('Run component test') {
            steps {
                sh 'cd backend && npm run test:compo'
            }
        }
        stage("Deploy") {
            steps {
                withCredentials([string(credentialsId: 'T04_host', variable: 'host'), 
                string(credentialsId: 'T04_USERNAME', variable: 'username'), 
                string(credentialsId: 'T04_BACKEND_PASS', variable: 'password')]) 
                {
                    script{
                        def remote = [:]
                        remote.name = 'T04'
                        remote.host = host
                        remote.user = username
                        remote.password = password
                        remote.allowAnyHosts = true
                         sshCommand remote: remote, command: "git clone https://github.com/panupongth148/Project-SW-DEV-TOOLS-AND-ENV-Group4.git"
                         sshCommand remote: remote, command: "docker-compose -f Project-SW-DEV-TOOLS-AND-ENV-Group4/docker-compose-build.yml build team-4-backend"
                         sshCommand remote: remote, command: "docker-compose -f team-4-backend up -d"
                        sshCommand remote: remote, command: "rm -r Project-SW-DEV-TOOLS-AND-ENV-Group4"
                    }
                }
            }
            }
    }
}
